package com.smile.dataModel;

// default package
// Generated Feb 9, 2018 2:57:47 AM by Hibernate Tools 5.2.8.Final

/**
 * BehaWd generated by hbm2java
 */
public class BehaWd implements java.io.Serializable {

	private String chinW;
	private int numFw;
	private String numPw;

	public BehaWd() {
	}

	public BehaWd(String chinW, int numFw, String numPw) {
		this.chinW = chinW;
		this.numFw = numFw;
		this.numPw = numPw;
	}

	public String getChinW() {
		return this.chinW;
	}

	public void setChinW(String chinW) {
		this.chinW = chinW;
	}

	public int getNumFw() {
		return this.numFw;
	}

	public void setNumFw(int numFw) {
		this.numFw = numFw;
	}

	public String getNumPw() {
		return this.numPw;
	}

	public void setNumPw(String numPw) {
		this.numPw = numPw;
	}

}
