package com.smile.dataModel;

// default package
// Generated Feb 9, 2018 2:57:47 AM by Hibernate Tools 5.2.8.Final

/**
 * Computer generated by hbm2java
 */
public class Computer implements java.io.Serializable {

	private String computerId;
	private String branchId;
	private String roomNo;
	private String songNo;

	public Computer() {
	}

	public Computer(String computerId, String branchId, String roomNo, String songNo) {
		this.computerId = computerId;
		this.branchId = branchId;
		this.roomNo = roomNo;
		this.songNo = songNo;
	}
	
    public void initiateRecordData() {
        setComputerId("");
        setBranchId("");
        setRoomNo("");
        setSongNo("");
    }

	public String getComputerId() {
		return this.computerId;
	}

	public void setComputerId(String computerId) {
		this.computerId = computerId;
	}

	public String getBranchId() {
		return this.branchId;
	}

	public void setBranchId(String branchId) {
		this.branchId = branchId;
	}

	public String getRoomNo() {
		return this.roomNo;
	}

	public void setRoomNo(String roomNo) {
		this.roomNo = roomNo;
	}

	public String getSongNo() {
		return this.songNo;
	}

	public void setSongNo(String songNo) {
		this.songNo = songNo;
	}

}
