package com.smile.dataModel;

// default package
// Generated Feb 9, 2018 2:57:47 AM by Hibernate Tools 5.2.8.Final

/**
 * Kkk2 generated by hbm2java
 */
public class Kkk2 implements java.io.Serializable {

	private String RNo;
	private String rmno;
	private String netNo;
	private String computerId;
	private String pwId;
	private boolean pwctTf;
	private int offTime;
	private int vvvId;
	private String romId;
	private boolean openTf;
	private boolean chckTf;
	private String tm;
	private boolean updTf;
	private boolean ejTf;
	private boolean dp8Tf;
	private boolean illegal;
	private String plSong;
	private String formNo;
	private String begTime;
	private boolean badTf;
	private String spNo;
	private String sn1;
	private String mult;
	private String repeat;
	private String servYn;
	private String enServ;
	private String disServ;
	private String castStr1;
	private String castStr2;
	private String castStr3;
	private String castAa;
	private boolean pause;
	private boolean ffward;
	private boolean upmusc;
	private boolean downmusc;
	private boolean upmic;
	private boolean downmic;
	private boolean upkey;
	private boolean downkey;
	private boolean stdkey;
	private boolean upecho;
	private boolean downecho;
	private boolean sp11;
	private boolean sp12;
	private boolean mute;
	private String mobile;

	public Kkk2() {
	}

	public Kkk2(String RNo, String rmno, String netNo, String computerId, String pwId, boolean pwctTf, int offTime,
			int vvvId, String romId, boolean openTf, boolean chckTf, String tm, boolean updTf, boolean ejTf,
			boolean dp8Tf, boolean illegal, String plSong, String formNo, String begTime, boolean badTf, String spNo,
			String sn1, String mult, String repeat, String servYn, String enServ, String disServ, String castStr1,
			String castStr2, String castStr3, String castAa, boolean pause, boolean ffward, boolean upmusc,
			boolean downmusc, boolean upmic, boolean downmic, boolean upkey, boolean downkey, boolean stdkey,
			boolean upecho, boolean downecho, boolean sp11, boolean sp12, boolean mute, String mobile) {
		this.RNo = RNo;
		this.rmno = rmno;
		this.netNo = netNo;
		this.computerId = computerId;
		this.pwId = pwId;
		this.pwctTf = pwctTf;
		this.offTime = offTime;
		this.vvvId = vvvId;
		this.romId = romId;
		this.openTf = openTf;
		this.chckTf = chckTf;
		this.tm = tm;
		this.updTf = updTf;
		this.ejTf = ejTf;
		this.dp8Tf = dp8Tf;
		this.illegal = illegal;
		this.plSong = plSong;
		this.formNo = formNo;
		this.begTime = begTime;
		this.badTf = badTf;
		this.spNo = spNo;
		this.sn1 = sn1;
		this.mult = mult;
		this.repeat = repeat;
		this.servYn = servYn;
		this.enServ = enServ;
		this.disServ = disServ;
		this.castStr1 = castStr1;
		this.castStr2 = castStr2;
		this.castStr3 = castStr3;
		this.castAa = castAa;
		this.pause = pause;
		this.ffward = ffward;
		this.upmusc = upmusc;
		this.downmusc = downmusc;
		this.upmic = upmic;
		this.downmic = downmic;
		this.upkey = upkey;
		this.downkey = downkey;
		this.stdkey = stdkey;
		this.upecho = upecho;
		this.downecho = downecho;
		this.sp11 = sp11;
		this.sp12 = sp12;
		this.mute = mute;
		this.mobile = mobile;
	}

	public String getRNo() {
		return this.RNo;
	}

	public void setRNo(String RNo) {
		this.RNo = RNo;
	}

	public String getRmno() {
		return this.rmno;
	}

	public void setRmno(String rmno) {
		this.rmno = rmno;
	}

	public String getNetNo() {
		return this.netNo;
	}

	public void setNetNo(String netNo) {
		this.netNo = netNo;
	}

	public String getComputerId() {
		return this.computerId;
	}

	public void setComputerId(String computerId) {
		this.computerId = computerId;
	}

	public String getPwId() {
		return this.pwId;
	}

	public void setPwId(String pwId) {
		this.pwId = pwId;
	}

	public boolean isPwctTf() {
		return this.pwctTf;
	}

	public void setPwctTf(boolean pwctTf) {
		this.pwctTf = pwctTf;
	}

	public int getOffTime() {
		return this.offTime;
	}

	public void setOffTime(int offTime) {
		this.offTime = offTime;
	}

	public int getVvvId() {
		return this.vvvId;
	}

	public void setVvvId(int vvvId) {
		this.vvvId = vvvId;
	}

	public String getRomId() {
		return this.romId;
	}

	public void setRomId(String romId) {
		this.romId = romId;
	}

	public boolean isOpenTf() {
		return this.openTf;
	}

	public void setOpenTf(boolean openTf) {
		this.openTf = openTf;
	}

	public boolean isChckTf() {
		return this.chckTf;
	}

	public void setChckTf(boolean chckTf) {
		this.chckTf = chckTf;
	}

	public String getTm() {
		return this.tm;
	}

	public void setTm(String tm) {
		this.tm = tm;
	}

	public boolean isUpdTf() {
		return this.updTf;
	}

	public void setUpdTf(boolean updTf) {
		this.updTf = updTf;
	}

	public boolean isEjTf() {
		return this.ejTf;
	}

	public void setEjTf(boolean ejTf) {
		this.ejTf = ejTf;
	}

	public boolean isDp8Tf() {
		return this.dp8Tf;
	}

	public void setDp8Tf(boolean dp8Tf) {
		this.dp8Tf = dp8Tf;
	}

	public boolean isIllegal() {
		return this.illegal;
	}

	public void setIllegal(boolean illegal) {
		this.illegal = illegal;
	}

	public String getPlSong() {
		return this.plSong;
	}

	public void setPlSong(String plSong) {
		this.plSong = plSong;
	}

	public String getFormNo() {
		return this.formNo;
	}

	public void setFormNo(String formNo) {
		this.formNo = formNo;
	}

	public String getBegTime() {
		return this.begTime;
	}

	public void setBegTime(String begTime) {
		this.begTime = begTime;
	}

	public boolean isBadTf() {
		return this.badTf;
	}

	public void setBadTf(boolean badTf) {
		this.badTf = badTf;
	}

	public String getSpNo() {
		return this.spNo;
	}

	public void setSpNo(String spNo) {
		this.spNo = spNo;
	}

	public String getSn1() {
		return this.sn1;
	}

	public void setSn1(String sn1) {
		this.sn1 = sn1;
	}

	public String getMult() {
		return this.mult;
	}

	public void setMult(String mult) {
		this.mult = mult;
	}

	public String getRepeat() {
		return this.repeat;
	}

	public void setRepeat(String repeat) {
		this.repeat = repeat;
	}

	public String getServYn() {
		return this.servYn;
	}

	public void setServYn(String servYn) {
		this.servYn = servYn;
	}

	public String getEnServ() {
		return this.enServ;
	}

	public void setEnServ(String enServ) {
		this.enServ = enServ;
	}

	public String getDisServ() {
		return this.disServ;
	}

	public void setDisServ(String disServ) {
		this.disServ = disServ;
	}

	public String getCastStr1() {
		return this.castStr1;
	}

	public void setCastStr1(String castStr1) {
		this.castStr1 = castStr1;
	}

	public String getCastStr2() {
		return this.castStr2;
	}

	public void setCastStr2(String castStr2) {
		this.castStr2 = castStr2;
	}

	public String getCastStr3() {
		return this.castStr3;
	}

	public void setCastStr3(String castStr3) {
		this.castStr3 = castStr3;
	}

	public String getCastAa() {
		return this.castAa;
	}

	public void setCastAa(String castAa) {
		this.castAa = castAa;
	}

	public boolean isPause() {
		return this.pause;
	}

	public void setPause(boolean pause) {
		this.pause = pause;
	}

	public boolean isFfward() {
		return this.ffward;
	}

	public void setFfward(boolean ffward) {
		this.ffward = ffward;
	}

	public boolean isUpmusc() {
		return this.upmusc;
	}

	public void setUpmusc(boolean upmusc) {
		this.upmusc = upmusc;
	}

	public boolean isDownmusc() {
		return this.downmusc;
	}

	public void setDownmusc(boolean downmusc) {
		this.downmusc = downmusc;
	}

	public boolean isUpmic() {
		return this.upmic;
	}

	public void setUpmic(boolean upmic) {
		this.upmic = upmic;
	}

	public boolean isDownmic() {
		return this.downmic;
	}

	public void setDownmic(boolean downmic) {
		this.downmic = downmic;
	}

	public boolean isUpkey() {
		return this.upkey;
	}

	public void setUpkey(boolean upkey) {
		this.upkey = upkey;
	}

	public boolean isDownkey() {
		return this.downkey;
	}

	public void setDownkey(boolean downkey) {
		this.downkey = downkey;
	}

	public boolean isStdkey() {
		return this.stdkey;
	}

	public void setStdkey(boolean stdkey) {
		this.stdkey = stdkey;
	}

	public boolean isUpecho() {
		return this.upecho;
	}

	public void setUpecho(boolean upecho) {
		this.upecho = upecho;
	}

	public boolean isDownecho() {
		return this.downecho;
	}

	public void setDownecho(boolean downecho) {
		this.downecho = downecho;
	}

	public boolean isSp11() {
		return this.sp11;
	}

	public void setSp11(boolean sp11) {
		this.sp11 = sp11;
	}

	public boolean isSp12() {
		return this.sp12;
	}

	public void setSp12(boolean sp12) {
		this.sp12 = sp12;
	}

	public boolean isMute() {
		return this.mute;
	}

	public void setMute(boolean mute) {
		this.mute = mute;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

}
