package com.smile.dataModel;

// default package
// Generated Feb 9, 2018 2:57:47 AM by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Language generated by hbm2java
 */
public class Language implements java.io.Serializable {

	private Integer id;
	private String langNo;
	private String langNa;
	private String langEn;
	private Set songs = new HashSet(0);

	public Language() {
	}

	public Language(String langNo, String langNa, String langEn) {
		this.langNo = langNo;
		this.langNa = langNa;
		this.langEn = langEn;
	}

	public Language(String langNo, String langNa, String langEn, Set songs) {
		this.langNo = langNo;
		this.langNa = langNa;
		this.langEn = langEn;
		this.songs = songs;
	}
	
	public void initiateLangurecord() {
        setLangNo("");
        setLangNa("");
        setLangEn("");
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getLangNo() {
		return this.langNo;
	}

	public void setLangNo(String langNo) {
		this.langNo = langNo;
	}

	public String getLangNa() {
		return this.langNa;
	}

	public void setLangNa(String langNa) {
		this.langNa = langNa;
	}

	public String getLangEn() {
		return this.langEn;
	}

	public void setLangEn(String langEn) {
		this.langEn = langEn;
	}

	public Set getSongs() {
		return this.songs;
	}

	public void setSongs(Set songs) {
		this.songs = songs;
	}

}
