package com.smile.dataModel;

// default package
// Generated Feb 9, 2018 2:57:47 AM by Hibernate Tools 5.2.8.Final

/**
 * Phonetic generated by hbm2java
 */
public class Phonetic implements java.io.Serializable {

	private String phnE;
	private String pinyin;
	private String pinyin2;
	private String chWord;

	public Phonetic() {
	}

	public Phonetic(String phnE, String pinyin, String pinyin2, String chWord) {
		this.phnE = phnE;
		this.pinyin = pinyin;
		this.pinyin2 = pinyin2;
		this.chWord = chWord;
	}

	public String getPhnE() {
		return this.phnE;
	}

	public void setPhnE(String phnE) {
		this.phnE = phnE;
	}

	public String getPinyin() {
		return this.pinyin;
	}

	public void setPinyin(String pinyin) {
		this.pinyin = pinyin;
	}

	public String getPinyin2() {
		return this.pinyin2;
	}

	public void setPinyin2(String pinyin2) {
		this.pinyin2 = pinyin2;
	}

	public String getChWord() {
		return this.chWord;
	}

	public void setChWord(String chWord) {
		this.chWord = chWord;
	}

}
