package com.smile.dataModel;

// default package
// Generated Feb 9, 2018 2:57:47 AM by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Singarea generated by hbm2java
 */
public class Singarea implements java.io.Serializable {

	private Integer id;
	private String areaTy;
	private String areaNa;
	private String areaEn;
	private Set singers = new HashSet(0);

	public Singarea() {
	}

	public Singarea(String areaTy, String areaNa, String areaEn) {
		this.areaTy = areaTy;
		this.areaNa = areaNa;
		this.areaEn = areaEn;
	}

	public Singarea(String areaTy, String areaNa, String areaEn, Set singers) {
		this.areaTy = areaTy;
		this.areaNa = areaNa;
		this.areaEn = areaEn;
		this.singers = singers;
	}
	
	public void initiateSingarearecord() {
        setAreaTy("");
        setAreaNa("");
        setAreaEn("");
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getAreaTy() {
		return this.areaTy;
	}

	public void setAreaTy(String areaTy) {
		this.areaTy = areaTy;
	}

	public String getAreaNa() {
		return this.areaNa;
	}

	public void setAreaNa(String areaNa) {
		this.areaNa = areaNa;
	}

	public String getAreaEn() {
		return this.areaEn;
	}

	public void setAreaEn(String areaEn) {
		this.areaEn = areaEn;
	}

	public Set getSingers() {
		return this.singers;
	}

	public void setSingers(Set singers) {
		this.singers = singers;
	}

}
