package com.smile.dataModel;

// default package
// Generated Feb 9, 2018 2:57:47 AM by Hibernate Tools 5.2.8.Final

/**
 * Singer generated by hbm2java
 */
public class Singer implements java.io.Serializable {

	private Integer id;
	private Singarea singarea;
	private String singNo;
	private String singNa;
	private int numFw;
	private String numPw;
	private String sex;
	private String chor;
	private String hot;
	private String picFile;

	public Singer() {
	}

	public Singer(Singarea singarea, String singNo, String singNa, int numFw, String numPw, String sex, String chor,
			String hot, String picFile) {
		this.singarea = singarea;
		this.singNo = singNo;
		this.singNa = singNa;
		this.numFw = numFw;
		this.numPw = numPw;
		this.sex = sex;
		this.chor = chor;
		this.hot = hot;
		this.picFile = picFile;
	}
	
	public void initiateSingerrecord() {
        setSingNo("");
        setSingNa("");
        setNumFw(0);
        setNumPw("");
        setSex("1");
        setChor("N");
        setHot("N");
        setPicFile("");
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Singarea getSingarea() {
		return this.singarea;
	}

	public void setSingarea(Singarea singarea) {
		this.singarea = singarea;
	}

	public String getSingNo() {
		return this.singNo;
	}

	public void setSingNo(String singNo) {
		this.singNo = singNo;
	}

	public String getSingNa() {
		return this.singNa;
	}

	public void setSingNa(String singNa) {
		this.singNa = singNa;
	}

	public int getNumFw() {
		return this.numFw;
	}

	public void setNumFw(int numFw) {
		this.numFw = numFw;
	}

	public String getNumPw() {
		return this.numPw;
	}

	public void setNumPw(String numPw) {
		this.numPw = numPw;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getChor() {
		return this.chor;
	}

	public void setChor(String chor) {
		this.chor = chor;
	}

	public String getHot() {
		return this.hot;
	}

	public void setHot(String hot) {
		this.hot = hot;
	}

	public String getPicFile() {
		return this.picFile;
	}

	public void setPicFile(String picFile) {
		this.picFile = picFile;
	}

}
