package com.smile.dataModel;

// default package
// Generated Feb 9, 2018 2:57:47 AM by Hibernate Tools 5.2.8.Final

import java.util.Date;

/**
 * Song generated by hbm2java
 */
public class Song implements java.io.Serializable {

	private Integer id;
	private Language language;
	private String songNo;
	private String songNa;
	private int SNumWord;
	private int numFw;
	private String numPw;
	private Byte seleTf;
	private String chor;
	private String NMpeg;
	private String MMpeg;
	private String vodYn;
	private String vodNo;
	private String pathname;
	private Integer ordNo;
	private Integer orderNum;
	private Integer ordOldN;
	private Date inDate;
	private int singer1Id;
	private int singer2Id;

	public Song() {
	}

	public Song(Language language, String songNo, String songNa, int SNumWord, int numFw, String numPw, String chor,
			String NMpeg, String MMpeg, String vodYn, String vodNo, String pathname, int singer1Id, int singer2Id) {
		this.language = language;
		this.songNo = songNo;
		this.songNa = songNa;
		this.SNumWord = SNumWord;
		this.numFw = numFw;
		this.numPw = numPw;
		this.chor = chor;
		this.NMpeg = NMpeg;
		this.MMpeg = MMpeg;
		this.vodYn = vodYn;
		this.vodNo = vodNo;
		this.pathname = pathname;
		this.singer1Id = singer1Id;
		this.singer2Id = singer2Id;
	}

	public Song(Language language, String songNo, String songNa, int SNumWord, int numFw, String numPw, Byte seleTf,
			String chor, String NMpeg, String MMpeg, String vodYn, String vodNo, String pathname, Integer ordNo,
			Integer orderNum, Integer ordOldN, Date inDate, int singer1Id, int singer2Id) {
		this.language = language;
		this.songNo = songNo;
		this.songNa = songNa;
		this.SNumWord = SNumWord;
		this.numFw = numFw;
		this.numPw = numPw;
		this.seleTf = seleTf;
		this.chor = chor;
		this.NMpeg = NMpeg;
		this.MMpeg = MMpeg;
		this.vodYn = vodYn;
		this.vodNo = vodNo;
		this.pathname = pathname;
		this.ordNo = ordNo;
		this.orderNum = orderNum;
		this.ordOldN = ordOldN;
		this.inDate = inDate;
		this.singer1Id = singer1Id;
		this.singer2Id = singer2Id;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Language getLanguage() {
		return this.language;
	}

	public void setLanguage(Language language) {
		this.language = language;
	}

	public String getSongNo() {
		return this.songNo;
	}

	public void setSongNo(String songNo) {
		this.songNo = songNo;
	}

	public String getSongNa() {
		return this.songNa;
	}

	public void setSongNa(String songNa) {
		this.songNa = songNa;
	}

	public int getSNumWord() {
		return this.SNumWord;
	}

	public void setSNumWord(int SNumWord) {
		this.SNumWord = SNumWord;
	}

	public int getNumFw() {
		return this.numFw;
	}

	public void setNumFw(int numFw) {
		this.numFw = numFw;
	}

	public String getNumPw() {
		return this.numPw;
	}

	public void setNumPw(String numPw) {
		this.numPw = numPw;
	}

	public Byte getSeleTf() {
		return this.seleTf;
	}

	public void setSeleTf(Byte seleTf) {
		this.seleTf = seleTf;
	}

	public String getChor() {
		return this.chor;
	}

	public void setChor(String chor) {
		this.chor = chor;
	}

	public String getNMpeg() {
		return this.NMpeg;
	}

	public void setNMpeg(String NMpeg) {
		this.NMpeg = NMpeg;
	}

	public String getMMpeg() {
		return this.MMpeg;
	}

	public void setMMpeg(String MMpeg) {
		this.MMpeg = MMpeg;
	}

	public String getVodYn() {
		return this.vodYn;
	}

	public void setVodYn(String vodYn) {
		this.vodYn = vodYn;
	}

	public String getVodNo() {
		return this.vodNo;
	}

	public void setVodNo(String vodNo) {
		this.vodNo = vodNo;
	}

	public String getPathname() {
		return this.pathname;
	}

	public void setPathname(String pathname) {
		this.pathname = pathname;
	}

	public Integer getOrdNo() {
		return this.ordNo;
	}

	public void setOrdNo(Integer ordNo) {
		this.ordNo = ordNo;
	}

	public Integer getOrderNum() {
		return this.orderNum;
	}

	public void setOrderNum(Integer orderNum) {
		this.orderNum = orderNum;
	}

	public Integer getOrdOldN() {
		return this.ordOldN;
	}

	public void setOrdOldN(Integer ordOldN) {
		this.ordOldN = ordOldN;
	}

	public Date getInDate() {
		return this.inDate;
	}

	public void setInDate(Date inDate) {
		this.inDate = inDate;
	}

	public int getSinger1Id() {
		return this.singer1Id;
	}

	public void setSinger1Id(int singer1Id) {
		this.singer1Id = singer1Id;
	}

	public int getSinger2Id() {
		return this.singer2Id;
	}

	public void setSinger2Id(int singer2Id) {
		this.singer2Id = singer2Id;
	}

}
